// Code generated by mockery v2.53.6. DO NOT EDIT.

package client

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "github.com/max-marek-projects/custodia/pkg/proto"
)

// MockClient is an autogenerated mock type for the CustodiaClient type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CreateSecret provides a mock function with given fields: ctx, in, opts
func (_m *MockClient) CreateSecret(ctx context.Context, in *proto.CreateSecretRequest, opts ...grpc.CallOption) (*proto.CreateSecretResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecret")
	}

	var r0 *proto.CreateSecretResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.CreateSecretRequest, ...grpc.CallOption) (*proto.CreateSecretResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.CreateSecretRequest, ...grpc.CallOption) *proto.CreateSecretResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.CreateSecretResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.CreateSecretRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_CreateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecret'
type MockClient_CreateSecret_Call struct {
	*mock.Call
}

// CreateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.CreateSecretRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) CreateSecret(ctx interface{}, in interface{}, opts ...interface{}) *MockClient_CreateSecret_Call {
	return &MockClient_CreateSecret_Call{Call: _e.mock.On("CreateSecret",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockClient_CreateSecret_Call) Run(run func(ctx context.Context, in *proto.CreateSecretRequest, opts ...grpc.CallOption)) *MockClient_CreateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.CreateSecretRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_CreateSecret_Call) Return(_a0 *proto.CreateSecretResponse, _a1 error) *MockClient_CreateSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_CreateSecret_Call) RunAndReturn(run func(context.Context, *proto.CreateSecretRequest, ...grpc.CallOption) (*proto.CreateSecretResponse, error)) *MockClient_CreateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecret provides a mock function with given fields: ctx, in, opts
func (_m *MockClient) DeleteSecret(ctx context.Context, in *proto.DeleteSecretRequest, opts ...grpc.CallOption) (*proto.DeleteSecretResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 *proto.DeleteSecretResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.DeleteSecretRequest, ...grpc.CallOption) (*proto.DeleteSecretResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.DeleteSecretRequest, ...grpc.CallOption) *proto.DeleteSecretResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.DeleteSecretResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.DeleteSecretRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_DeleteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecret'
type MockClient_DeleteSecret_Call struct {
	*mock.Call
}

// DeleteSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.DeleteSecretRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) DeleteSecret(ctx interface{}, in interface{}, opts ...interface{}) *MockClient_DeleteSecret_Call {
	return &MockClient_DeleteSecret_Call{Call: _e.mock.On("DeleteSecret",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockClient_DeleteSecret_Call) Run(run func(ctx context.Context, in *proto.DeleteSecretRequest, opts ...grpc.CallOption)) *MockClient_DeleteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.DeleteSecretRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_DeleteSecret_Call) Return(_a0 *proto.DeleteSecretResponse, _a1 error) *MockClient_DeleteSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_DeleteSecret_Call) RunAndReturn(run func(context.Context, *proto.DeleteSecretRequest, ...grpc.CallOption) (*proto.DeleteSecretResponse, error)) *MockClient_DeleteSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function with given fields: ctx, in, opts
func (_m *MockClient) GetSecret(ctx context.Context, in *proto.GetSecretRequest, opts ...grpc.CallOption) (*proto.GetSecretResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 *proto.GetSecretResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetSecretRequest, ...grpc.CallOption) (*proto.GetSecretResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetSecretRequest, ...grpc.CallOption) *proto.GetSecretResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GetSecretResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetSecretRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockClient_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.GetSecretRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) GetSecret(ctx interface{}, in interface{}, opts ...interface{}) *MockClient_GetSecret_Call {
	return &MockClient_GetSecret_Call{Call: _e.mock.On("GetSecret",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockClient_GetSecret_Call) Run(run func(ctx context.Context, in *proto.GetSecretRequest, opts ...grpc.CallOption)) *MockClient_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.GetSecretRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_GetSecret_Call) Return(_a0 *proto.GetSecretResponse, _a1 error) *MockClient_GetSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetSecret_Call) RunAndReturn(run func(context.Context, *proto.GetSecretRequest, ...grpc.CallOption) (*proto.GetSecretResponse, error)) *MockClient_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecrets provides a mock function with given fields: ctx, in, opts
func (_m *MockClient) ListSecrets(ctx context.Context, in *proto.ListSecretsRequest, opts ...grpc.CallOption) (*proto.ListSecretsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListSecrets")
	}

	var r0 *proto.ListSecretsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.ListSecretsRequest, ...grpc.CallOption) (*proto.ListSecretsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.ListSecretsRequest, ...grpc.CallOption) *proto.ListSecretsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.ListSecretsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.ListSecretsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecrets'
type MockClient_ListSecrets_Call struct {
	*mock.Call
}

// ListSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.ListSecretsRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) ListSecrets(ctx interface{}, in interface{}, opts ...interface{}) *MockClient_ListSecrets_Call {
	return &MockClient_ListSecrets_Call{Call: _e.mock.On("ListSecrets",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockClient_ListSecrets_Call) Run(run func(ctx context.Context, in *proto.ListSecretsRequest, opts ...grpc.CallOption)) *MockClient_ListSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.ListSecretsRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_ListSecrets_Call) Return(_a0 *proto.ListSecretsResponse, _a1 error) *MockClient_ListSecrets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListSecrets_Call) RunAndReturn(run func(context.Context, *proto.ListSecretsRequest, ...grpc.CallOption) (*proto.ListSecretsResponse, error)) *MockClient_ListSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// LoginUser provides a mock function with given fields: ctx, in, opts
func (_m *MockClient) LoginUser(ctx context.Context, in *proto.LoginRequest, opts ...grpc.CallOption) (*proto.LoginResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LoginUser")
	}

	var r0 *proto.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.LoginRequest, ...grpc.CallOption) (*proto.LoginResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.LoginRequest, ...grpc.CallOption) *proto.LoginResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.LoginRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_LoginUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginUser'
type MockClient_LoginUser_Call struct {
	*mock.Call
}

// LoginUser is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.LoginRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) LoginUser(ctx interface{}, in interface{}, opts ...interface{}) *MockClient_LoginUser_Call {
	return &MockClient_LoginUser_Call{Call: _e.mock.On("LoginUser",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockClient_LoginUser_Call) Run(run func(ctx context.Context, in *proto.LoginRequest, opts ...grpc.CallOption)) *MockClient_LoginUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.LoginRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_LoginUser_Call) Return(_a0 *proto.LoginResponse, _a1 error) *MockClient_LoginUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_LoginUser_Call) RunAndReturn(run func(context.Context, *proto.LoginRequest, ...grpc.CallOption) (*proto.LoginResponse, error)) *MockClient_LoginUser_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutAllDevices provides a mock function with given fields: ctx, in, opts
func (_m *MockClient) LogoutAllDevices(ctx context.Context, in *proto.LogoutAllDevicesRequest, opts ...grpc.CallOption) (*proto.LogoutAllDevicesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LogoutAllDevices")
	}

	var r0 *proto.LogoutAllDevicesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.LogoutAllDevicesRequest, ...grpc.CallOption) (*proto.LogoutAllDevicesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.LogoutAllDevicesRequest, ...grpc.CallOption) *proto.LogoutAllDevicesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.LogoutAllDevicesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.LogoutAllDevicesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_LogoutAllDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutAllDevices'
type MockClient_LogoutAllDevices_Call struct {
	*mock.Call
}

// LogoutAllDevices is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.LogoutAllDevicesRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) LogoutAllDevices(ctx interface{}, in interface{}, opts ...interface{}) *MockClient_LogoutAllDevices_Call {
	return &MockClient_LogoutAllDevices_Call{Call: _e.mock.On("LogoutAllDevices",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockClient_LogoutAllDevices_Call) Run(run func(ctx context.Context, in *proto.LogoutAllDevicesRequest, opts ...grpc.CallOption)) *MockClient_LogoutAllDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.LogoutAllDevicesRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_LogoutAllDevices_Call) Return(_a0 *proto.LogoutAllDevicesResponse, _a1 error) *MockClient_LogoutAllDevices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_LogoutAllDevices_Call) RunAndReturn(run func(context.Context, *proto.LogoutAllDevicesRequest, ...grpc.CallOption) (*proto.LogoutAllDevicesResponse, error)) *MockClient_LogoutAllDevices_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutDevice provides a mock function with given fields: ctx, in, opts
func (_m *MockClient) LogoutDevice(ctx context.Context, in *proto.LogoutDeviceRequest, opts ...grpc.CallOption) (*proto.LogoutDeviceResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LogoutDevice")
	}

	var r0 *proto.LogoutDeviceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.LogoutDeviceRequest, ...grpc.CallOption) (*proto.LogoutDeviceResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.LogoutDeviceRequest, ...grpc.CallOption) *proto.LogoutDeviceResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.LogoutDeviceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.LogoutDeviceRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_LogoutDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutDevice'
type MockClient_LogoutDevice_Call struct {
	*mock.Call
}

// LogoutDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.LogoutDeviceRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) LogoutDevice(ctx interface{}, in interface{}, opts ...interface{}) *MockClient_LogoutDevice_Call {
	return &MockClient_LogoutDevice_Call{Call: _e.mock.On("LogoutDevice",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockClient_LogoutDevice_Call) Run(run func(ctx context.Context, in *proto.LogoutDeviceRequest, opts ...grpc.CallOption)) *MockClient_LogoutDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.LogoutDeviceRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_LogoutDevice_Call) Return(_a0 *proto.LogoutDeviceResponse, _a1 error) *MockClient_LogoutDevice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_LogoutDevice_Call) RunAndReturn(run func(context.Context, *proto.LogoutDeviceRequest, ...grpc.CallOption) (*proto.LogoutDeviceResponse, error)) *MockClient_LogoutDevice_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, in, opts
func (_m *MockClient) Refresh(ctx context.Context, in *proto.RefreshRequest, opts ...grpc.CallOption) (*proto.RefreshResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *proto.RefreshResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.RefreshRequest, ...grpc.CallOption) (*proto.RefreshResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.RefreshRequest, ...grpc.CallOption) *proto.RefreshResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.RefreshResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.RefreshRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockClient_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.RefreshRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) Refresh(ctx interface{}, in interface{}, opts ...interface{}) *MockClient_Refresh_Call {
	return &MockClient_Refresh_Call{Call: _e.mock.On("Refresh",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockClient_Refresh_Call) Run(run func(ctx context.Context, in *proto.RefreshRequest, opts ...grpc.CallOption)) *MockClient_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.RefreshRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_Refresh_Call) Return(_a0 *proto.RefreshResponse, _a1 error) *MockClient_Refresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Refresh_Call) RunAndReturn(run func(context.Context, *proto.RefreshRequest, ...grpc.CallOption) (*proto.RefreshResponse, error)) *MockClient_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function with given fields: ctx, in, opts
func (_m *MockClient) RegisterUser(ctx context.Context, in *proto.LoginRequest, opts ...grpc.CallOption) (*proto.LoginResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 *proto.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.LoginRequest, ...grpc.CallOption) (*proto.LoginResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.LoginRequest, ...grpc.CallOption) *proto.LoginResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.LoginRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockClient_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.LoginRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) RegisterUser(ctx interface{}, in interface{}, opts ...interface{}) *MockClient_RegisterUser_Call {
	return &MockClient_RegisterUser_Call{Call: _e.mock.On("RegisterUser",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockClient_RegisterUser_Call) Run(run func(ctx context.Context, in *proto.LoginRequest, opts ...grpc.CallOption)) *MockClient_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.LoginRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_RegisterUser_Call) Return(_a0 *proto.LoginResponse, _a1 error) *MockClient_RegisterUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_RegisterUser_Call) RunAndReturn(run func(context.Context, *proto.LoginRequest, ...grpc.CallOption) (*proto.LoginResponse, error)) *MockClient_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackSecret provides a mock function with given fields: ctx, in, opts
func (_m *MockClient) RollbackSecret(ctx context.Context, in *proto.RollbackSecretRequest, opts ...grpc.CallOption) (*proto.RollbackSecretResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RollbackSecret")
	}

	var r0 *proto.RollbackSecretResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.RollbackSecretRequest, ...grpc.CallOption) (*proto.RollbackSecretResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.RollbackSecretRequest, ...grpc.CallOption) *proto.RollbackSecretResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.RollbackSecretResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.RollbackSecretRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_RollbackSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackSecret'
type MockClient_RollbackSecret_Call struct {
	*mock.Call
}

// RollbackSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.RollbackSecretRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) RollbackSecret(ctx interface{}, in interface{}, opts ...interface{}) *MockClient_RollbackSecret_Call {
	return &MockClient_RollbackSecret_Call{Call: _e.mock.On("RollbackSecret",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockClient_RollbackSecret_Call) Run(run func(ctx context.Context, in *proto.RollbackSecretRequest, opts ...grpc.CallOption)) *MockClient_RollbackSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.RollbackSecretRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_RollbackSecret_Call) Return(_a0 *proto.RollbackSecretResponse, _a1 error) *MockClient_RollbackSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_RollbackSecret_Call) RunAndReturn(run func(context.Context, *proto.RollbackSecretRequest, ...grpc.CallOption) (*proto.RollbackSecretResponse, error)) *MockClient_RollbackSecret_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSecretData provides a mock function with given fields: ctx, in, opts
func (_m *MockClient) UpdateSecretData(ctx context.Context, in *proto.UpdateSecretDataRequest, opts ...grpc.CallOption) (*proto.UpdateSecretDataResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecretData")
	}

	var r0 *proto.UpdateSecretDataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateSecretDataRequest, ...grpc.CallOption) (*proto.UpdateSecretDataResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateSecretDataRequest, ...grpc.CallOption) *proto.UpdateSecretDataResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.UpdateSecretDataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.UpdateSecretDataRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_UpdateSecretData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSecretData'
type MockClient_UpdateSecretData_Call struct {
	*mock.Call
}

// UpdateSecretData is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.UpdateSecretDataRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) UpdateSecretData(ctx interface{}, in interface{}, opts ...interface{}) *MockClient_UpdateSecretData_Call {
	return &MockClient_UpdateSecretData_Call{Call: _e.mock.On("UpdateSecretData",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockClient_UpdateSecretData_Call) Run(run func(ctx context.Context, in *proto.UpdateSecretDataRequest, opts ...grpc.CallOption)) *MockClient_UpdateSecretData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.UpdateSecretDataRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_UpdateSecretData_Call) Return(_a0 *proto.UpdateSecretDataResponse, _a1 error) *MockClient_UpdateSecretData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_UpdateSecretData_Call) RunAndReturn(run func(context.Context, *proto.UpdateSecretDataRequest, ...grpc.CallOption) (*proto.UpdateSecretDataResponse, error)) *MockClient_UpdateSecretData_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSecretMetadata provides a mock function with given fields: ctx, in, opts
func (_m *MockClient) UpdateSecretMetadata(ctx context.Context, in *proto.UpdateSecretMetadataRequest, opts ...grpc.CallOption) (*proto.UpdateSecretMetadataResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecretMetadata")
	}

	var r0 *proto.UpdateSecretMetadataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateSecretMetadataRequest, ...grpc.CallOption) (*proto.UpdateSecretMetadataResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateSecretMetadataRequest, ...grpc.CallOption) *proto.UpdateSecretMetadataResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.UpdateSecretMetadataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.UpdateSecretMetadataRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_UpdateSecretMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSecretMetadata'
type MockClient_UpdateSecretMetadata_Call struct {
	*mock.Call
}

// UpdateSecretMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.UpdateSecretMetadataRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) UpdateSecretMetadata(ctx interface{}, in interface{}, opts ...interface{}) *MockClient_UpdateSecretMetadata_Call {
	return &MockClient_UpdateSecretMetadata_Call{Call: _e.mock.On("UpdateSecretMetadata",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockClient_UpdateSecretMetadata_Call) Run(run func(ctx context.Context, in *proto.UpdateSecretMetadataRequest, opts ...grpc.CallOption)) *MockClient_UpdateSecretMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.UpdateSecretMetadataRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_UpdateSecretMetadata_Call) Return(_a0 *proto.UpdateSecretMetadataResponse, _a1 error) *MockClient_UpdateSecretMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_UpdateSecretMetadata_Call) RunAndReturn(run func(context.Context, *proto.UpdateSecretMetadataRequest, ...grpc.CallOption) (*proto.UpdateSecretMetadataResponse, error)) *MockClient_UpdateSecretMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
