// Code generated by mockery v2.53.6. DO NOT EDIT.

package service

import (
	context "context"

	models "github.com/max-marek-projects/custodia/internal/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// CheckRefreshToken provides a mock function with given fields: ctx, userID, tokenHash, deviceName
func (_m *MockStorage) CheckRefreshToken(ctx context.Context, userID int64, tokenHash []byte, deviceName string) error {
	ret := _m.Called(ctx, userID, tokenHash, deviceName)

	if len(ret) == 0 {
		panic("no return value specified for CheckRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []byte, string) error); ok {
		r0 = rf(ctx, userID, tokenHash, deviceName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_CheckRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckRefreshToken'
type MockStorage_CheckRefreshToken_Call struct {
	*mock.Call
}

// CheckRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - tokenHash []byte
//   - deviceName string
func (_e *MockStorage_Expecter) CheckRefreshToken(ctx interface{}, userID interface{}, tokenHash interface{}, deviceName interface{}) *MockStorage_CheckRefreshToken_Call {
	return &MockStorage_CheckRefreshToken_Call{Call: _e.mock.On("CheckRefreshToken", ctx, userID, tokenHash, deviceName)}
}

func (_c *MockStorage_CheckRefreshToken_Call) Run(run func(ctx context.Context, userID int64, tokenHash []byte, deviceName string)) *MockStorage_CheckRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]byte), args[3].(string))
	})
	return _c
}

func (_c *MockStorage_CheckRefreshToken_Call) Return(_a0 error) *MockStorage_CheckRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_CheckRefreshToken_Call) RunAndReturn(run func(context.Context, int64, []byte, string) error) *MockStorage_CheckRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// CheckUser provides a mock function with given fields: ctx, username
func (_m *MockStorage) CheckUser(ctx context.Context, username string) (int64, []byte, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for CheckUser")
	}

	var r0 int64
	var r1 []byte
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, []byte, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) []byte); ok {
		r1 = rf(ctx, username)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, username)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStorage_CheckUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUser'
type MockStorage_CheckUser_Call struct {
	*mock.Call
}

// CheckUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockStorage_Expecter) CheckUser(ctx interface{}, username interface{}) *MockStorage_CheckUser_Call {
	return &MockStorage_CheckUser_Call{Call: _e.mock.On("CheckUser", ctx, username)}
}

func (_c *MockStorage_CheckUser_Call) Run(run func(ctx context.Context, username string)) *MockStorage_CheckUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_CheckUser_Call) Return(_a0 int64, _a1 []byte, _a2 error) *MockStorage_CheckUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStorage_CheckUser_Call) RunAndReturn(run func(context.Context, string) (int64, []byte, error)) *MockStorage_CheckUser_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields: ctx
func (_m *MockStorage) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStorage_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) Close(ctx interface{}) *MockStorage_Close_Call {
	return &MockStorage_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockStorage_Close_Call) Run(run func(ctx context.Context)) *MockStorage_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStorage_Close_Call) Return(_a0 error) *MockStorage_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Close_Call) RunAndReturn(run func(context.Context) error) *MockStorage_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSecret provides a mock function with given fields: ctx, userID, dataType, name, data, salt, iv, metadata
func (_m *MockStorage) CreateSecret(ctx context.Context, userID int64, dataType models.DataType, name string, data []byte, salt []byte, iv []byte, metadata map[string]string) error {
	ret := _m.Called(ctx, userID, dataType, name, data, salt, iv, metadata)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.DataType, string, []byte, []byte, []byte, map[string]string) error); ok {
		r0 = rf(ctx, userID, dataType, name, data, salt, iv, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_CreateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecret'
type MockStorage_CreateSecret_Call struct {
	*mock.Call
}

// CreateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - dataType models.DataType
//   - name string
//   - data []byte
//   - salt []byte
//   - iv []byte
//   - metadata map[string]string
func (_e *MockStorage_Expecter) CreateSecret(ctx interface{}, userID interface{}, dataType interface{}, name interface{}, data interface{}, salt interface{}, iv interface{}, metadata interface{}) *MockStorage_CreateSecret_Call {
	return &MockStorage_CreateSecret_Call{Call: _e.mock.On("CreateSecret", ctx, userID, dataType, name, data, salt, iv, metadata)}
}

func (_c *MockStorage_CreateSecret_Call) Run(run func(ctx context.Context, userID int64, dataType models.DataType, name string, data []byte, salt []byte, iv []byte, metadata map[string]string)) *MockStorage_CreateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(models.DataType), args[3].(string), args[4].([]byte), args[5].([]byte), args[6].([]byte), args[7].(map[string]string))
	})
	return _c
}

func (_c *MockStorage_CreateSecret_Call) Return(_a0 error) *MockStorage_CreateSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_CreateSecret_Call) RunAndReturn(run func(context.Context, int64, models.DataType, string, []byte, []byte, []byte, map[string]string) error) *MockStorage_CreateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecret provides a mock function with given fields: ctx, userID, name
func (_m *MockStorage) DeleteSecret(ctx context.Context, userID int64, name string) error {
	ret := _m.Called(ctx, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, userID, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecret'
type MockStorage_DeleteSecret_Call struct {
	*mock.Call
}

// DeleteSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - name string
func (_e *MockStorage_Expecter) DeleteSecret(ctx interface{}, userID interface{}, name interface{}) *MockStorage_DeleteSecret_Call {
	return &MockStorage_DeleteSecret_Call{Call: _e.mock.On("DeleteSecret", ctx, userID, name)}
}

func (_c *MockStorage_DeleteSecret_Call) Run(run func(ctx context.Context, userID int64, name string)) *MockStorage_DeleteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockStorage_DeleteSecret_Call) Return(_a0 error) *MockStorage_DeleteSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteSecret_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockStorage_DeleteSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function with given fields: ctx, userID, dataType, name, version
func (_m *MockStorage) GetSecret(ctx context.Context, userID int64, dataType models.DataType, name string, version uint64) ([]byte, []byte, []byte, map[string]string, error) {
	ret := _m.Called(ctx, userID, dataType, name, version)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 []byte
	var r1 []byte
	var r2 []byte
	var r3 map[string]string
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.DataType, string, uint64) ([]byte, []byte, []byte, map[string]string, error)); ok {
		return rf(ctx, userID, dataType, name, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.DataType, string, uint64) []byte); ok {
		r0 = rf(ctx, userID, dataType, name, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, models.DataType, string, uint64) []byte); ok {
		r1 = rf(ctx, userID, dataType, name, version)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, models.DataType, string, uint64) []byte); ok {
		r2 = rf(ctx, userID, dataType, name, version)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).([]byte)
		}
	}

	if rf, ok := ret.Get(3).(func(context.Context, int64, models.DataType, string, uint64) map[string]string); ok {
		r3 = rf(ctx, userID, dataType, name, version)
	} else {
		if ret.Get(3) != nil {
			r3 = ret.Get(3).(map[string]string)
		}
	}

	if rf, ok := ret.Get(4).(func(context.Context, int64, models.DataType, string, uint64) error); ok {
		r4 = rf(ctx, userID, dataType, name, version)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// MockStorage_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockStorage_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - dataType models.DataType
//   - name string
//   - version uint64
func (_e *MockStorage_Expecter) GetSecret(ctx interface{}, userID interface{}, dataType interface{}, name interface{}, version interface{}) *MockStorage_GetSecret_Call {
	return &MockStorage_GetSecret_Call{Call: _e.mock.On("GetSecret", ctx, userID, dataType, name, version)}
}

func (_c *MockStorage_GetSecret_Call) Run(run func(ctx context.Context, userID int64, dataType models.DataType, name string, version uint64)) *MockStorage_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(models.DataType), args[3].(string), args[4].(uint64))
	})
	return _c
}

func (_c *MockStorage_GetSecret_Call) Return(data []byte, salt []byte, iv []byte, metadata map[string]string, err error) *MockStorage_GetSecret_Call {
	_c.Call.Return(data, salt, iv, metadata, err)
	return _c
}

func (_c *MockStorage_GetSecret_Call) RunAndReturn(run func(context.Context, int64, models.DataType, string, uint64) ([]byte, []byte, []byte, map[string]string, error)) *MockStorage_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecrets provides a mock function with given fields: ctx, userID, filter
func (_m *MockStorage) ListSecrets(ctx context.Context, userID int64, filter map[string]string) ([]models.SecretInfo, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListSecrets")
	}

	var r0 []models.SecretInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, map[string]string) ([]models.SecretInfo, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, map[string]string) []models.SecretInfo); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.SecretInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, map[string]string) error); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_ListSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecrets'
type MockStorage_ListSecrets_Call struct {
	*mock.Call
}

// ListSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - filter map[string]string
func (_e *MockStorage_Expecter) ListSecrets(ctx interface{}, userID interface{}, filter interface{}) *MockStorage_ListSecrets_Call {
	return &MockStorage_ListSecrets_Call{Call: _e.mock.On("ListSecrets", ctx, userID, filter)}
}

func (_c *MockStorage_ListSecrets_Call) Run(run func(ctx context.Context, userID int64, filter map[string]string)) *MockStorage_ListSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(map[string]string))
	})
	return _c
}

func (_c *MockStorage_ListSecrets_Call) Return(_a0 []models.SecretInfo, _a1 error) *MockStorage_ListSecrets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_ListSecrets_Call) RunAndReturn(run func(context.Context, int64, map[string]string) ([]models.SecretInfo, error)) *MockStorage_ListSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function with given fields: ctx, userData
func (_m *MockStorage) RegisterUser(ctx context.Context, userData models.UserData) (int64, error) {
	ret := _m.Called(ctx, userData)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserData) (int64, error)); ok {
		return rf(ctx, userData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserData) int64); ok {
		r0 = rf(ctx, userData)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserData) error); ok {
		r1 = rf(ctx, userData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockStorage_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userData models.UserData
func (_e *MockStorage_Expecter) RegisterUser(ctx interface{}, userData interface{}) *MockStorage_RegisterUser_Call {
	return &MockStorage_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, userData)}
}

func (_c *MockStorage_RegisterUser_Call) Run(run func(ctx context.Context, userData models.UserData)) *MockStorage_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UserData))
	})
	return _c
}

func (_c *MockStorage_RegisterUser_Call) Return(_a0 int64, _a1 error) *MockStorage_RegisterUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_RegisterUser_Call) RunAndReturn(run func(context.Context, models.UserData) (int64, error)) *MockStorage_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllTokens provides a mock function with given fields: ctx, userID
func (_m *MockStorage) RevokeAllTokens(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_RevokeAllTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllTokens'
type MockStorage_RevokeAllTokens_Call struct {
	*mock.Call
}

// RevokeAllTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockStorage_Expecter) RevokeAllTokens(ctx interface{}, userID interface{}) *MockStorage_RevokeAllTokens_Call {
	return &MockStorage_RevokeAllTokens_Call{Call: _e.mock.On("RevokeAllTokens", ctx, userID)}
}

func (_c *MockStorage_RevokeAllTokens_Call) Run(run func(ctx context.Context, userID int64)) *MockStorage_RevokeAllTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockStorage_RevokeAllTokens_Call) Return(_a0 error) *MockStorage_RevokeAllTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_RevokeAllTokens_Call) RunAndReturn(run func(context.Context, int64) error) *MockStorage_RevokeAllTokens_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function with given fields: ctx, userID, deviceName
func (_m *MockStorage) RevokeToken(ctx context.Context, userID int64, deviceName string) error {
	ret := _m.Called(ctx, userID, deviceName)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, userID, deviceName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type MockStorage_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - deviceName string
func (_e *MockStorage_Expecter) RevokeToken(ctx interface{}, userID interface{}, deviceName interface{}) *MockStorage_RevokeToken_Call {
	return &MockStorage_RevokeToken_Call{Call: _e.mock.On("RevokeToken", ctx, userID, deviceName)}
}

func (_c *MockStorage_RevokeToken_Call) Run(run func(ctx context.Context, userID int64, deviceName string)) *MockStorage_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockStorage_RevokeToken_Call) Return(_a0 error) *MockStorage_RevokeToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_RevokeToken_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockStorage_RevokeToken_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackSecret provides a mock function with given fields: ctx, userID, name
func (_m *MockStorage) RollbackSecret(ctx context.Context, userID int64, name string) error {
	ret := _m.Called(ctx, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for RollbackSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, userID, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_RollbackSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackSecret'
type MockStorage_RollbackSecret_Call struct {
	*mock.Call
}

// RollbackSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - name string
func (_e *MockStorage_Expecter) RollbackSecret(ctx interface{}, userID interface{}, name interface{}) *MockStorage_RollbackSecret_Call {
	return &MockStorage_RollbackSecret_Call{Call: _e.mock.On("RollbackSecret", ctx, userID, name)}
}

func (_c *MockStorage_RollbackSecret_Call) Run(run func(ctx context.Context, userID int64, name string)) *MockStorage_RollbackSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockStorage_RollbackSecret_Call) Return(_a0 error) *MockStorage_RollbackSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_RollbackSecret_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockStorage_RollbackSecret_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRefreshToken provides a mock function with given fields: ctx, userID, tokenHash, deviceName, ttl
func (_m *MockStorage) SaveRefreshToken(ctx context.Context, userID int64, tokenHash []byte, deviceName string, ttl time.Duration) error {
	ret := _m.Called(ctx, userID, tokenHash, deviceName, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SaveRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []byte, string, time.Duration) error); ok {
		r0 = rf(ctx, userID, tokenHash, deviceName, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_SaveRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRefreshToken'
type MockStorage_SaveRefreshToken_Call struct {
	*mock.Call
}

// SaveRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - tokenHash []byte
//   - deviceName string
//   - ttl time.Duration
func (_e *MockStorage_Expecter) SaveRefreshToken(ctx interface{}, userID interface{}, tokenHash interface{}, deviceName interface{}, ttl interface{}) *MockStorage_SaveRefreshToken_Call {
	return &MockStorage_SaveRefreshToken_Call{Call: _e.mock.On("SaveRefreshToken", ctx, userID, tokenHash, deviceName, ttl)}
}

func (_c *MockStorage_SaveRefreshToken_Call) Run(run func(ctx context.Context, userID int64, tokenHash []byte, deviceName string, ttl time.Duration)) *MockStorage_SaveRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]byte), args[3].(string), args[4].(time.Duration))
	})
	return _c
}

func (_c *MockStorage_SaveRefreshToken_Call) Return(_a0 error) *MockStorage_SaveRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_SaveRefreshToken_Call) RunAndReturn(run func(context.Context, int64, []byte, string, time.Duration) error) *MockStorage_SaveRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSecret provides a mock function with given fields: ctx, userID, name, data, salt, iv, metadata
func (_m *MockStorage) UpdateSecret(ctx context.Context, userID int64, name string, data []byte, salt []byte, iv []byte, metadata map[string]string) error {
	ret := _m.Called(ctx, userID, name, data, salt, iv, metadata)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, []byte, []byte, []byte, map[string]string) error); ok {
		r0 = rf(ctx, userID, name, data, salt, iv, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSecret'
type MockStorage_UpdateSecret_Call struct {
	*mock.Call
}

// UpdateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - name string
//   - data []byte
//   - salt []byte
//   - iv []byte
//   - metadata map[string]string
func (_e *MockStorage_Expecter) UpdateSecret(ctx interface{}, userID interface{}, name interface{}, data interface{}, salt interface{}, iv interface{}, metadata interface{}) *MockStorage_UpdateSecret_Call {
	return &MockStorage_UpdateSecret_Call{Call: _e.mock.On("UpdateSecret", ctx, userID, name, data, salt, iv, metadata)}
}

func (_c *MockStorage_UpdateSecret_Call) Run(run func(ctx context.Context, userID int64, name string, data []byte, salt []byte, iv []byte, metadata map[string]string)) *MockStorage_UpdateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].([]byte), args[4].([]byte), args[5].([]byte), args[6].(map[string]string))
	})
	return _c
}

func (_c *MockStorage_UpdateSecret_Call) Return(_a0 error) *MockStorage_UpdateSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateSecret_Call) RunAndReturn(run func(context.Context, int64, string, []byte, []byte, []byte, map[string]string) error) *MockStorage_UpdateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
