// Code generated by mockery v2.53.6. DO NOT EDIT.

package handlers

import (
	context "context"

	models "github.com/max-marek-projects/custodia/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateSecret provides a mock function with given fields: ctx, userID, dataType, name, data, salt, iv, metadata
func (_m *MockService) CreateSecret(ctx context.Context, userID int64, dataType models.DataType, name string, data []byte, salt []byte, iv []byte, metadata map[string]string) error {
	ret := _m.Called(ctx, userID, dataType, name, data, salt, iv, metadata)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.DataType, string, []byte, []byte, []byte, map[string]string) error); ok {
		r0 = rf(ctx, userID, dataType, name, data, salt, iv, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_CreateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecret'
type MockService_CreateSecret_Call struct {
	*mock.Call
}

// CreateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - dataType models.DataType
//   - name string
//   - data []byte
//   - salt []byte
//   - iv []byte
//   - metadata map[string]string
func (_e *MockService_Expecter) CreateSecret(ctx any, userID any, dataType any, name any, data any, salt any, iv any, metadata any) *MockService_CreateSecret_Call {
	return &MockService_CreateSecret_Call{Call: _e.mock.On("CreateSecret", ctx, userID, dataType, name, data, salt, iv, metadata)}
}

func (_c *MockService_CreateSecret_Call) Run(run func(ctx context.Context, userID int64, dataType models.DataType, name string, data []byte, salt []byte, iv []byte, metadata map[string]string)) *MockService_CreateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(models.DataType), args[3].(string), args[4].([]byte), args[5].([]byte), args[6].([]byte), args[7].(map[string]string))
	})
	return _c
}

func (_c *MockService_CreateSecret_Call) Return(_a0 error) *MockService_CreateSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_CreateSecret_Call) RunAndReturn(run func(context.Context, int64, models.DataType, string, []byte, []byte, []byte, map[string]string) error) *MockService_CreateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecret provides a mock function with given fields: ctx, userID, name
func (_m *MockService) DeleteSecret(ctx context.Context, userID int64, name string) error {
	ret := _m.Called(ctx, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, userID, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecret'
type MockService_DeleteSecret_Call struct {
	*mock.Call
}

// DeleteSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - name string
func (_e *MockService_Expecter) DeleteSecret(ctx any, userID any, name any) *MockService_DeleteSecret_Call {
	return &MockService_DeleteSecret_Call{Call: _e.mock.On("DeleteSecret", ctx, userID, name)}
}

func (_c *MockService_DeleteSecret_Call) Run(run func(ctx context.Context, userID int64, name string)) *MockService_DeleteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeleteSecret_Call) Return(_a0 error) *MockService_DeleteSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteSecret_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockService_DeleteSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function with given fields: ctx, userID, dataType, name, version
func (_m *MockService) GetSecret(ctx context.Context, userID int64, dataType models.DataType, name string, version uint64) ([]byte, []byte, []byte, map[string]string, error) {
	ret := _m.Called(ctx, userID, dataType, name, version)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 []byte
	var r1 []byte
	var r2 []byte
	var r3 map[string]string
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.DataType, string, uint64) ([]byte, []byte, []byte, map[string]string, error)); ok {
		return rf(ctx, userID, dataType, name, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.DataType, string, uint64) []byte); ok {
		r0 = rf(ctx, userID, dataType, name, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, models.DataType, string, uint64) []byte); ok {
		r1 = rf(ctx, userID, dataType, name, version)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, models.DataType, string, uint64) []byte); ok {
		r2 = rf(ctx, userID, dataType, name, version)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).([]byte)
		}
	}

	if rf, ok := ret.Get(3).(func(context.Context, int64, models.DataType, string, uint64) map[string]string); ok {
		r3 = rf(ctx, userID, dataType, name, version)
	} else {
		if ret.Get(3) != nil {
			r3 = ret.Get(3).(map[string]string)
		}
	}

	if rf, ok := ret.Get(4).(func(context.Context, int64, models.DataType, string, uint64) error); ok {
		r4 = rf(ctx, userID, dataType, name, version)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// MockService_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockService_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - dataType models.DataType
//   - name string
//   - version uint64
func (_e *MockService_Expecter) GetSecret(ctx any, userID any, dataType any, name any, version any) *MockService_GetSecret_Call {
	return &MockService_GetSecret_Call{Call: _e.mock.On("GetSecret", ctx, userID, dataType, name, version)}
}

func (_c *MockService_GetSecret_Call) Run(run func(ctx context.Context, userID int64, dataType models.DataType, name string, version uint64)) *MockService_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(models.DataType), args[3].(string), args[4].(uint64))
	})
	return _c
}

func (_c *MockService_GetSecret_Call) Return(data []byte, salt []byte, iv []byte, metadata map[string]string, err error) *MockService_GetSecret_Call {
	_c.Call.Return(data, salt, iv, metadata, err)
	return _c
}

func (_c *MockService_GetSecret_Call) RunAndReturn(run func(context.Context, int64, models.DataType, string, uint64) ([]byte, []byte, []byte, map[string]string, error)) *MockService_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// LoginUser provides a mock function with given fields: ctx, userData
func (_m *MockService) LoginUser(ctx context.Context, userData *models.LoginRequest) (*models.LoginResponse, error) {
	ret := _m.Called(ctx, userData)

	if len(ret) == 0 {
		panic("no return value specified for LoginUser")
	}

	var r0 *models.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.LoginRequest) (*models.LoginResponse, error)); ok {
		return rf(ctx, userData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.LoginRequest) *models.LoginResponse); ok {
		r0 = rf(ctx, userData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.LoginRequest) error); ok {
		r1 = rf(ctx, userData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_LoginUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginUser'
type MockService_LoginUser_Call struct {
	*mock.Call
}

// LoginUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userData *models.LoginRequest
func (_e *MockService_Expecter) LoginUser(ctx any, userData any) *MockService_LoginUser_Call {
	return &MockService_LoginUser_Call{Call: _e.mock.On("LoginUser", ctx, userData)}
}

func (_c *MockService_LoginUser_Call) Run(run func(ctx context.Context, userData *models.LoginRequest)) *MockService_LoginUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.LoginRequest))
	})
	return _c
}

func (_c *MockService_LoginUser_Call) Return(_a0 *models.LoginResponse, _a1 error) *MockService_LoginUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_LoginUser_Call) RunAndReturn(run func(context.Context, *models.LoginRequest) (*models.LoginResponse, error)) *MockService_LoginUser_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, userID, deviceName
func (_m *MockService) Logout(ctx context.Context, userID int64, deviceName string) error {
	ret := _m.Called(ctx, userID, deviceName)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, userID, deviceName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - deviceName string
func (_e *MockService_Expecter) Logout(ctx any, userID any, deviceName any) *MockService_Logout_Call {
	return &MockService_Logout_Call{Call: _e.mock.On("Logout", ctx, userID, deviceName)}
}

func (_c *MockService_Logout_Call) Run(run func(ctx context.Context, userID int64, deviceName string)) *MockService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockService_Logout_Call) Return(_a0 error) *MockService_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Logout_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutAllDevices provides a mock function with given fields: ctx, userID
func (_m *MockService) LogoutAllDevices(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for LogoutAllDevices")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_LogoutAllDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutAllDevices'
type MockService_LogoutAllDevices_Call struct {
	*mock.Call
}

// LogoutAllDevices is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockService_Expecter) LogoutAllDevices(ctx any, userID any) *MockService_LogoutAllDevices_Call {
	return &MockService_LogoutAllDevices_Call{Call: _e.mock.On("LogoutAllDevices", ctx, userID)}
}

func (_c *MockService_LogoutAllDevices_Call) Run(run func(ctx context.Context, userID int64)) *MockService_LogoutAllDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockService_LogoutAllDevices_Call) Return(_a0 error) *MockService_LogoutAllDevices_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_LogoutAllDevices_Call) RunAndReturn(run func(context.Context, int64) error) *MockService_LogoutAllDevices_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshAccess provides a mock function with given fields: ctx, userID, refreshToken, deviceName
func (_m *MockService) RefreshAccess(ctx context.Context, userID int64, refreshToken []byte, deviceName string) (string, error) {
	ret := _m.Called(ctx, userID, refreshToken, deviceName)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAccess")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []byte, string) (string, error)); ok {
		return rf(ctx, userID, refreshToken, deviceName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, []byte, string) string); ok {
		r0 = rf(ctx, userID, refreshToken, deviceName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, []byte, string) error); ok {
		r1 = rf(ctx, userID, refreshToken, deviceName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_RefreshAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshAccess'
type MockService_RefreshAccess_Call struct {
	*mock.Call
}

// RefreshAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - refreshToken []byte
//   - deviceName string
func (_e *MockService_Expecter) RefreshAccess(ctx any, userID any, refreshToken any, deviceName any) *MockService_RefreshAccess_Call {
	return &MockService_RefreshAccess_Call{Call: _e.mock.On("RefreshAccess", ctx, userID, refreshToken, deviceName)}
}

func (_c *MockService_RefreshAccess_Call) Run(run func(ctx context.Context, userID int64, refreshToken []byte, deviceName string)) *MockService_RefreshAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]byte), args[3].(string))
	})
	return _c
}

func (_c *MockService_RefreshAccess_Call) Return(_a0 string, _a1 error) *MockService_RefreshAccess_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_RefreshAccess_Call) RunAndReturn(run func(context.Context, int64, []byte, string) (string, error)) *MockService_RefreshAccess_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function with given fields: ctx, userData
func (_m *MockService) RegisterUser(ctx context.Context, userData *models.LoginRequest) (*models.LoginResponse, error) {
	ret := _m.Called(ctx, userData)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 *models.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.LoginRequest) (*models.LoginResponse, error)); ok {
		return rf(ctx, userData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.LoginRequest) *models.LoginResponse); ok {
		r0 = rf(ctx, userData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.LoginRequest) error); ok {
		r1 = rf(ctx, userData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockService_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userData *models.LoginRequest
func (_e *MockService_Expecter) RegisterUser(ctx any, userData any) *MockService_RegisterUser_Call {
	return &MockService_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, userData)}
}

func (_c *MockService_RegisterUser_Call) Run(run func(ctx context.Context, userData *models.LoginRequest)) *MockService_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.LoginRequest))
	})
	return _c
}

func (_c *MockService_RegisterUser_Call) Return(_a0 *models.LoginResponse, _a1 error) *MockService_RegisterUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_RegisterUser_Call) RunAndReturn(run func(context.Context, *models.LoginRequest) (*models.LoginResponse, error)) *MockService_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackSecret provides a mock function with given fields: ctx, userID, name
func (_m *MockService) RollbackSecret(ctx context.Context, userID int64, name string) error {
	ret := _m.Called(ctx, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for RollbackSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, userID, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_RollbackSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackSecret'
type MockService_RollbackSecret_Call struct {
	*mock.Call
}

// RollbackSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - name string
func (_e *MockService_Expecter) RollbackSecret(ctx any, userID any, name any) *MockService_RollbackSecret_Call {
	return &MockService_RollbackSecret_Call{Call: _e.mock.On("RollbackSecret", ctx, userID, name)}
}

func (_c *MockService_RollbackSecret_Call) Run(run func(ctx context.Context, userID int64, name string)) *MockService_RollbackSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockService_RollbackSecret_Call) Return(_a0 error) *MockService_RollbackSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_RollbackSecret_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockService_RollbackSecret_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSecretData provides a mock function with given fields: ctx, userID, name, data, salt, iv
func (_m *MockService) UpdateSecretData(ctx context.Context, userID int64, name string, data []byte, salt []byte, iv []byte) error {
	ret := _m.Called(ctx, userID, name, data, salt, iv)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecretData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, []byte, []byte, []byte) error); ok {
		r0 = rf(ctx, userID, name, data, salt, iv)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_UpdateSecretData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSecretData'
type MockService_UpdateSecretData_Call struct {
	*mock.Call
}

// UpdateSecretData is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - name string
//   - data []byte
//   - salt []byte
//   - iv []byte
func (_e *MockService_Expecter) UpdateSecretData(ctx any, userID any, name any, data any, salt any, iv any) *MockService_UpdateSecretData_Call {
	return &MockService_UpdateSecretData_Call{Call: _e.mock.On("UpdateSecretData", ctx, userID, name, data, salt, iv)}
}

func (_c *MockService_UpdateSecretData_Call) Run(run func(ctx context.Context, userID int64, name string, data []byte, salt []byte, iv []byte)) *MockService_UpdateSecretData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].([]byte), args[4].([]byte), args[5].([]byte))
	})
	return _c
}

func (_c *MockService_UpdateSecretData_Call) Return(_a0 error) *MockService_UpdateSecretData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_UpdateSecretData_Call) RunAndReturn(run func(context.Context, int64, string, []byte, []byte, []byte) error) *MockService_UpdateSecretData_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSecretMetadata provides a mock function with given fields: ctx, userID, name, metadata
func (_m *MockService) UpdateSecretMetadata(ctx context.Context, userID int64, name string, metadata map[string]string) error {
	ret := _m.Called(ctx, userID, name, metadata)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecretMetadata")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, map[string]string) error); ok {
		r0 = rf(ctx, userID, name, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_UpdateSecretMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSecretMetadata'
type MockService_UpdateSecretMetadata_Call struct {
	*mock.Call
}

// UpdateSecretMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - name string
//   - metadata map[string]string
func (_e *MockService_Expecter) UpdateSecretMetadata(ctx any, userID any, name any, metadata any) *MockService_UpdateSecretMetadata_Call {
	return &MockService_UpdateSecretMetadata_Call{Call: _e.mock.On("UpdateSecretMetadata", ctx, userID, name, metadata)}
}

func (_c *MockService_UpdateSecretMetadata_Call) Run(run func(ctx context.Context, userID int64, name string, metadata map[string]string)) *MockService_UpdateSecretMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(map[string]string))
	})
	return _c
}

func (_c *MockService_UpdateSecretMetadata_Call) Return(_a0 error) *MockService_UpdateSecretMetadata_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_UpdateSecretMetadata_Call) RunAndReturn(run func(context.Context, int64, string, map[string]string) error) *MockService_UpdateSecretMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
