// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0--rc2
// source: api/custodia.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Custodia_RegisterUser_FullMethodName         = "/custodia.Custodia/RegisterUser"
	Custodia_LoginUser_FullMethodName            = "/custodia.Custodia/LoginUser"
	Custodia_Refresh_FullMethodName              = "/custodia.Custodia/Refresh"
	Custodia_LogoutDevice_FullMethodName         = "/custodia.Custodia/LogoutDevice"
	Custodia_LogoutAllDevices_FullMethodName     = "/custodia.Custodia/LogoutAllDevices"
	Custodia_CreateSecret_FullMethodName         = "/custodia.Custodia/CreateSecret"
	Custodia_GetSecret_FullMethodName            = "/custodia.Custodia/GetSecret"
	Custodia_RollbackSecret_FullMethodName       = "/custodia.Custodia/RollbackSecret"
	Custodia_DeleteSecret_FullMethodName         = "/custodia.Custodia/DeleteSecret"
	Custodia_UpdateSecretData_FullMethodName     = "/custodia.Custodia/UpdateSecretData"
	Custodia_UpdateSecretMetadata_FullMethodName = "/custodia.Custodia/UpdateSecretMetadata"
	Custodia_ListSecrets_FullMethodName          = "/custodia.Custodia/ListSecrets"
)

// CustodiaClient is the client API for Custodia service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustodiaClient interface {
	// ========== AUTH ==========
	RegisterUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	LoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error)
	LogoutDevice(ctx context.Context, in *LogoutDeviceRequest, opts ...grpc.CallOption) (*LogoutDeviceResponse, error)
	LogoutAllDevices(ctx context.Context, in *LogoutAllDevicesRequest, opts ...grpc.CallOption) (*LogoutAllDevicesResponse, error)
	// ========== SECRETS ==========
	CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...grpc.CallOption) (*CreateSecretResponse, error)
	GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error)
	RollbackSecret(ctx context.Context, in *RollbackSecretRequest, opts ...grpc.CallOption) (*RollbackSecretResponse, error)
	DeleteSecret(ctx context.Context, in *DeleteSecretRequest, opts ...grpc.CallOption) (*DeleteSecretResponse, error)
	UpdateSecretData(ctx context.Context, in *UpdateSecretDataRequest, opts ...grpc.CallOption) (*UpdateSecretDataResponse, error)
	UpdateSecretMetadata(ctx context.Context, in *UpdateSecretMetadataRequest, opts ...grpc.CallOption) (*UpdateSecretMetadataResponse, error)
	ListSecrets(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error)
}

type custodiaClient struct {
	cc grpc.ClientConnInterface
}

func NewCustodiaClient(cc grpc.ClientConnInterface) CustodiaClient {
	return &custodiaClient{cc}
}

func (c *custodiaClient) RegisterUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, Custodia_RegisterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *custodiaClient) LoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, Custodia_LoginUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *custodiaClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshResponse)
	err := c.cc.Invoke(ctx, Custodia_Refresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *custodiaClient) LogoutDevice(ctx context.Context, in *LogoutDeviceRequest, opts ...grpc.CallOption) (*LogoutDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutDeviceResponse)
	err := c.cc.Invoke(ctx, Custodia_LogoutDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *custodiaClient) LogoutAllDevices(ctx context.Context, in *LogoutAllDevicesRequest, opts ...grpc.CallOption) (*LogoutAllDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutAllDevicesResponse)
	err := c.cc.Invoke(ctx, Custodia_LogoutAllDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *custodiaClient) CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...grpc.CallOption) (*CreateSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSecretResponse)
	err := c.cc.Invoke(ctx, Custodia_CreateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *custodiaClient) GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecretResponse)
	err := c.cc.Invoke(ctx, Custodia_GetSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *custodiaClient) RollbackSecret(ctx context.Context, in *RollbackSecretRequest, opts ...grpc.CallOption) (*RollbackSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackSecretResponse)
	err := c.cc.Invoke(ctx, Custodia_RollbackSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *custodiaClient) DeleteSecret(ctx context.Context, in *DeleteSecretRequest, opts ...grpc.CallOption) (*DeleteSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSecretResponse)
	err := c.cc.Invoke(ctx, Custodia_DeleteSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *custodiaClient) UpdateSecretData(ctx context.Context, in *UpdateSecretDataRequest, opts ...grpc.CallOption) (*UpdateSecretDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSecretDataResponse)
	err := c.cc.Invoke(ctx, Custodia_UpdateSecretData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *custodiaClient) UpdateSecretMetadata(ctx context.Context, in *UpdateSecretMetadataRequest, opts ...grpc.CallOption) (*UpdateSecretMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSecretMetadataResponse)
	err := c.cc.Invoke(ctx, Custodia_UpdateSecretMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *custodiaClient) ListSecrets(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSecretsResponse)
	err := c.cc.Invoke(ctx, Custodia_ListSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustodiaServer is the server API for Custodia service.
// All implementations must embed UnimplementedCustodiaServer
// for forward compatibility.
type CustodiaServer interface {
	// ========== AUTH ==========
	RegisterUser(context.Context, *LoginRequest) (*LoginResponse, error)
	LoginUser(context.Context, *LoginRequest) (*LoginResponse, error)
	Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error)
	LogoutDevice(context.Context, *LogoutDeviceRequest) (*LogoutDeviceResponse, error)
	LogoutAllDevices(context.Context, *LogoutAllDevicesRequest) (*LogoutAllDevicesResponse, error)
	// ========== SECRETS ==========
	CreateSecret(context.Context, *CreateSecretRequest) (*CreateSecretResponse, error)
	GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error)
	RollbackSecret(context.Context, *RollbackSecretRequest) (*RollbackSecretResponse, error)
	DeleteSecret(context.Context, *DeleteSecretRequest) (*DeleteSecretResponse, error)
	UpdateSecretData(context.Context, *UpdateSecretDataRequest) (*UpdateSecretDataResponse, error)
	UpdateSecretMetadata(context.Context, *UpdateSecretMetadataRequest) (*UpdateSecretMetadataResponse, error)
	ListSecrets(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error)
	mustEmbedUnimplementedCustodiaServer()
}

// UnimplementedCustodiaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCustodiaServer struct{}

func (UnimplementedCustodiaServer) RegisterUser(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedCustodiaServer) LoginUser(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedCustodiaServer) Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedCustodiaServer) LogoutDevice(context.Context, *LogoutDeviceRequest) (*LogoutDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LogoutDevice not implemented")
}
func (UnimplementedCustodiaServer) LogoutAllDevices(context.Context, *LogoutAllDevicesRequest) (*LogoutAllDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LogoutAllDevices not implemented")
}
func (UnimplementedCustodiaServer) CreateSecret(context.Context, *CreateSecretRequest) (*CreateSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSecret not implemented")
}
func (UnimplementedCustodiaServer) GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecret not implemented")
}
func (UnimplementedCustodiaServer) RollbackSecret(context.Context, *RollbackSecretRequest) (*RollbackSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackSecret not implemented")
}
func (UnimplementedCustodiaServer) DeleteSecret(context.Context, *DeleteSecretRequest) (*DeleteSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSecret not implemented")
}
func (UnimplementedCustodiaServer) UpdateSecretData(context.Context, *UpdateSecretDataRequest) (*UpdateSecretDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSecretData not implemented")
}
func (UnimplementedCustodiaServer) UpdateSecretMetadata(context.Context, *UpdateSecretMetadataRequest) (*UpdateSecretMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSecretMetadata not implemented")
}
func (UnimplementedCustodiaServer) ListSecrets(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSecrets not implemented")
}
func (UnimplementedCustodiaServer) mustEmbedUnimplementedCustodiaServer() {}
func (UnimplementedCustodiaServer) testEmbeddedByValue()                  {}

// UnsafeCustodiaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustodiaServer will
// result in compilation errors.
type UnsafeCustodiaServer interface {
	mustEmbedUnimplementedCustodiaServer()
}

func RegisterCustodiaServer(s grpc.ServiceRegistrar, srv CustodiaServer) {
	// If the following call panics, it indicates UnimplementedCustodiaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Custodia_ServiceDesc, srv)
}

func _Custodia_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustodiaServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Custodia_RegisterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustodiaServer).RegisterUser(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Custodia_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustodiaServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Custodia_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustodiaServer).LoginUser(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Custodia_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustodiaServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Custodia_Refresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustodiaServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Custodia_LogoutDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustodiaServer).LogoutDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Custodia_LogoutDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustodiaServer).LogoutDevice(ctx, req.(*LogoutDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Custodia_LogoutAllDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutAllDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustodiaServer).LogoutAllDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Custodia_LogoutAllDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustodiaServer).LogoutAllDevices(ctx, req.(*LogoutAllDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Custodia_CreateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustodiaServer).CreateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Custodia_CreateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustodiaServer).CreateSecret(ctx, req.(*CreateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Custodia_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustodiaServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Custodia_GetSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustodiaServer).GetSecret(ctx, req.(*GetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Custodia_RollbackSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustodiaServer).RollbackSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Custodia_RollbackSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustodiaServer).RollbackSecret(ctx, req.(*RollbackSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Custodia_DeleteSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustodiaServer).DeleteSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Custodia_DeleteSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustodiaServer).DeleteSecret(ctx, req.(*DeleteSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Custodia_UpdateSecretData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSecretDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustodiaServer).UpdateSecretData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Custodia_UpdateSecretData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustodiaServer).UpdateSecretData(ctx, req.(*UpdateSecretDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Custodia_UpdateSecretMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSecretMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustodiaServer).UpdateSecretMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Custodia_UpdateSecretMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustodiaServer).UpdateSecretMetadata(ctx, req.(*UpdateSecretMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Custodia_ListSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustodiaServer).ListSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Custodia_ListSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustodiaServer).ListSecrets(ctx, req.(*ListSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Custodia_ServiceDesc is the grpc.ServiceDesc for Custodia service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Custodia_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "custodia.Custodia",
	HandlerType: (*CustodiaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _Custodia_RegisterUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _Custodia_LoginUser_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _Custodia_Refresh_Handler,
		},
		{
			MethodName: "LogoutDevice",
			Handler:    _Custodia_LogoutDevice_Handler,
		},
		{
			MethodName: "LogoutAllDevices",
			Handler:    _Custodia_LogoutAllDevices_Handler,
		},
		{
			MethodName: "CreateSecret",
			Handler:    _Custodia_CreateSecret_Handler,
		},
		{
			MethodName: "GetSecret",
			Handler:    _Custodia_GetSecret_Handler,
		},
		{
			MethodName: "RollbackSecret",
			Handler:    _Custodia_RollbackSecret_Handler,
		},
		{
			MethodName: "DeleteSecret",
			Handler:    _Custodia_DeleteSecret_Handler,
		},
		{
			MethodName: "UpdateSecretData",
			Handler:    _Custodia_UpdateSecretData_Handler,
		},
		{
			MethodName: "UpdateSecretMetadata",
			Handler:    _Custodia_UpdateSecretMetadata_Handler,
		},
		{
			MethodName: "ListSecrets",
			Handler:    _Custodia_ListSecrets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/custodia.proto",
}
