// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0--rc2
// source: api/custodia.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Custodia_RegisterUser_FullMethodName     = "/custodia.Custodia/RegisterUser"
	Custodia_LoginUser_FullMethodName        = "/custodia.Custodia/LoginUser"
	Custodia_Refresh_FullMethodName          = "/custodia.Custodia/Refresh"
	Custodia_LogoutDevice_FullMethodName     = "/custodia.Custodia/LogoutDevice"
	Custodia_LogoutAllDevices_FullMethodName = "/custodia.Custodia/LogoutAllDevices"
)

// CustodiaClient is the client API for Custodia service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustodiaClient interface {
	RegisterUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	LoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error)
	LogoutDevice(ctx context.Context, in *LogoutDeviceRequest, opts ...grpc.CallOption) (*LogoutDeviceResponse, error)
	LogoutAllDevices(ctx context.Context, in *LogoutAllDevicesRequest, opts ...grpc.CallOption) (*LogoutAllDevicesResponse, error)
}

type custodiaClient struct {
	cc grpc.ClientConnInterface
}

func NewCustodiaClient(cc grpc.ClientConnInterface) CustodiaClient {
	return &custodiaClient{cc}
}

func (c *custodiaClient) RegisterUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, Custodia_RegisterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *custodiaClient) LoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, Custodia_LoginUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *custodiaClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshResponse)
	err := c.cc.Invoke(ctx, Custodia_Refresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *custodiaClient) LogoutDevice(ctx context.Context, in *LogoutDeviceRequest, opts ...grpc.CallOption) (*LogoutDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutDeviceResponse)
	err := c.cc.Invoke(ctx, Custodia_LogoutDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *custodiaClient) LogoutAllDevices(ctx context.Context, in *LogoutAllDevicesRequest, opts ...grpc.CallOption) (*LogoutAllDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutAllDevicesResponse)
	err := c.cc.Invoke(ctx, Custodia_LogoutAllDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustodiaServer is the server API for Custodia service.
// All implementations must embed UnimplementedCustodiaServer
// for forward compatibility.
type CustodiaServer interface {
	RegisterUser(context.Context, *LoginRequest) (*LoginResponse, error)
	LoginUser(context.Context, *LoginRequest) (*LoginResponse, error)
	Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error)
	LogoutDevice(context.Context, *LogoutDeviceRequest) (*LogoutDeviceResponse, error)
	LogoutAllDevices(context.Context, *LogoutAllDevicesRequest) (*LogoutAllDevicesResponse, error)
	mustEmbedUnimplementedCustodiaServer()
}

// UnimplementedCustodiaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCustodiaServer struct{}

func (UnimplementedCustodiaServer) RegisterUser(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedCustodiaServer) LoginUser(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedCustodiaServer) Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedCustodiaServer) LogoutDevice(context.Context, *LogoutDeviceRequest) (*LogoutDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LogoutDevice not implemented")
}
func (UnimplementedCustodiaServer) LogoutAllDevices(context.Context, *LogoutAllDevicesRequest) (*LogoutAllDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LogoutAllDevices not implemented")
}
func (UnimplementedCustodiaServer) mustEmbedUnimplementedCustodiaServer() {}
func (UnimplementedCustodiaServer) testEmbeddedByValue()                  {}

// UnsafeCustodiaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustodiaServer will
// result in compilation errors.
type UnsafeCustodiaServer interface {
	mustEmbedUnimplementedCustodiaServer()
}

func RegisterCustodiaServer(s grpc.ServiceRegistrar, srv CustodiaServer) {
	// If the following call panics, it indicates UnimplementedCustodiaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Custodia_ServiceDesc, srv)
}

func _Custodia_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustodiaServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Custodia_RegisterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustodiaServer).RegisterUser(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Custodia_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustodiaServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Custodia_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustodiaServer).LoginUser(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Custodia_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustodiaServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Custodia_Refresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustodiaServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Custodia_LogoutDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustodiaServer).LogoutDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Custodia_LogoutDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustodiaServer).LogoutDevice(ctx, req.(*LogoutDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Custodia_LogoutAllDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutAllDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustodiaServer).LogoutAllDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Custodia_LogoutAllDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustodiaServer).LogoutAllDevices(ctx, req.(*LogoutAllDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Custodia_ServiceDesc is the grpc.ServiceDesc for Custodia service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Custodia_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "custodia.Custodia",
	HandlerType: (*CustodiaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _Custodia_RegisterUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _Custodia_LoginUser_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _Custodia_Refresh_Handler,
		},
		{
			MethodName: "LogoutDevice",
			Handler:    _Custodia_LogoutDevice_Handler,
		},
		{
			MethodName: "LogoutAllDevices",
			Handler:    _Custodia_LogoutAllDevices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/custodia.proto",
}
