// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0--rc2
// source: api/custodia.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login      string                 `protobuf:"bytes,1,opt,name=login,proto3"`
	xxx_hidden_Password   string                 `protobuf:"bytes,2,opt,name=password,proto3"`
	xxx_hidden_DeviceName string                 `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_custodia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_custodia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.xxx_hidden_Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return ""
}

func (x *LoginRequest) GetDeviceName() string {
	if x != nil {
		return x.xxx_hidden_DeviceName
	}
	return ""
}

func (x *LoginRequest) SetLogin(v string) {
	x.xxx_hidden_Login = v
}

func (x *LoginRequest) SetPassword(v string) {
	x.xxx_hidden_Password = v
}

func (x *LoginRequest) SetDeviceName(v string) {
	x.xxx_hidden_DeviceName = v
}

type LoginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login      string
	Password   string
	DeviceName string
}

func (b0 LoginRequest_builder) Build() *LoginRequest {
	m0 := &LoginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Login = b.Login
	x.xxx_hidden_Password = b.Password
	x.xxx_hidden_DeviceName = b.DeviceName
	return m0
}

type LoginResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserId       int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3"`
	xxx_hidden_AccessToken  string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3"`
	xxx_hidden_RefreshToken []byte                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_custodia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_custodia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginResponse) GetUserId() int64 {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return 0
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() []byte {
	if x != nil {
		return x.xxx_hidden_RefreshToken
	}
	return nil
}

func (x *LoginResponse) SetUserId(v int64) {
	x.xxx_hidden_UserId = v
}

func (x *LoginResponse) SetAccessToken(v string) {
	x.xxx_hidden_AccessToken = v
}

func (x *LoginResponse) SetRefreshToken(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_RefreshToken = v
}

type LoginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId       int64
	AccessToken  string
	RefreshToken []byte
}

func (b0 LoginResponse_builder) Build() *LoginResponse {
	m0 := &LoginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_AccessToken = b.AccessToken
	x.xxx_hidden_RefreshToken = b.RefreshToken
	return m0
}

type RefreshRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserId       int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3"`
	xxx_hidden_RefreshToken []byte                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3"`
	xxx_hidden_DeviceName   string                 `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_api_custodia_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_custodia_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RefreshRequest) GetUserId() int64 {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return 0
}

func (x *RefreshRequest) GetRefreshToken() []byte {
	if x != nil {
		return x.xxx_hidden_RefreshToken
	}
	return nil
}

func (x *RefreshRequest) GetDeviceName() string {
	if x != nil {
		return x.xxx_hidden_DeviceName
	}
	return ""
}

func (x *RefreshRequest) SetUserId(v int64) {
	x.xxx_hidden_UserId = v
}

func (x *RefreshRequest) SetRefreshToken(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_RefreshToken = v
}

func (x *RefreshRequest) SetDeviceName(v string) {
	x.xxx_hidden_DeviceName = v
}

type RefreshRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId       int64
	RefreshToken []byte
	DeviceName   string
}

func (b0 RefreshRequest_builder) Build() *RefreshRequest {
	m0 := &RefreshRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_RefreshToken = b.RefreshToken
	x.xxx_hidden_DeviceName = b.DeviceName
	return m0
}

type RefreshResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AccessToken string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_api_custodia_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_custodia_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RefreshResponse) GetAccessToken() string {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return ""
}

func (x *RefreshResponse) SetAccessToken(v string) {
	x.xxx_hidden_AccessToken = v
}

type RefreshResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AccessToken string
}

func (b0 RefreshResponse_builder) Build() *RefreshResponse {
	m0 := &RefreshResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AccessToken = b.AccessToken
	return m0
}

var File_api_custodia_proto protoreflect.FileDescriptor

const file_api_custodia_proto_rawDesc = "" +
	"\n" +
	"\x12api/custodia.proto\x12\bcustodia\"a\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\"p\n" +
	"\rLoginResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\fR\frefreshToken\"o\n" +
	"\x0eRefreshRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\fR\frefreshToken\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\"4\n" +
	"\x0fRefreshResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken2\xc9\x01\n" +
	"\bCustodia\x12?\n" +
	"\fRegisterUser\x12\x16.custodia.LoginRequest\x1a\x17.custodia.LoginResponse\x12<\n" +
	"\tLoginUser\x12\x16.custodia.LoginRequest\x1a\x17.custodia.LoginResponse\x12>\n" +
	"\aRefresh\x12\x18.custodia.RefreshRequest\x1a\x19.custodia.RefreshResponseB8Z6github.com/max-marek-projects/custodia/pkg/proto;protob\x06proto3"

var file_api_custodia_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_custodia_proto_goTypes = []any{
	(*LoginRequest)(nil),    // 0: custodia.LoginRequest
	(*LoginResponse)(nil),   // 1: custodia.LoginResponse
	(*RefreshRequest)(nil),  // 2: custodia.RefreshRequest
	(*RefreshResponse)(nil), // 3: custodia.RefreshResponse
}
var file_api_custodia_proto_depIdxs = []int32{
	0, // 0: custodia.Custodia.RegisterUser:input_type -> custodia.LoginRequest
	0, // 1: custodia.Custodia.LoginUser:input_type -> custodia.LoginRequest
	2, // 2: custodia.Custodia.Refresh:input_type -> custodia.RefreshRequest
	1, // 3: custodia.Custodia.RegisterUser:output_type -> custodia.LoginResponse
	1, // 4: custodia.Custodia.LoginUser:output_type -> custodia.LoginResponse
	3, // 5: custodia.Custodia.Refresh:output_type -> custodia.RefreshResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_custodia_proto_init() }
func file_api_custodia_proto_init() {
	if File_api_custodia_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_custodia_proto_rawDesc), len(file_api_custodia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_custodia_proto_goTypes,
		DependencyIndexes: file_api_custodia_proto_depIdxs,
		MessageInfos:      file_api_custodia_proto_msgTypes,
	}.Build()
	File_api_custodia_proto = out.File
	file_api_custodia_proto_goTypes = nil
	file_api_custodia_proto_depIdxs = nil
}
